version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "80"
      volumes:
          - ./app:/var/app
      environment:
          - VIRTUAL_HOST=drinkglo.docker,staging.drinkglo.com
          - VIRTUAL_PORT=80
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=glo"      
  db:
      image: mariadb
      environment:
          - MYSQL_DATABASE=glo      
          - MYSQL_ROOT_PASSWORD=L0v3Gl0

#      volumes:
#          - ./database:/var/lib/mysql
